-- MySQL Script generated by MySQL Workbench
-- 08/11/17 11:17:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `nome_empresa` VARCHAR(45) NOT NULL,
  `endereco_empresa` VARCHAR(60) NULL,
  `telefone_empresa` VARCHAR(20) NOT NULL,
  `login_empresa` VARCHAR(20) NOT NULL,
  `senha_empresa` VARCHAR(20) NOT NULL,
  `funcionamento_empresa` ENUM('ABERTO', 'FECHADO') NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(45) NOT NULL,
  `preco_produto` REAL NOT NULL,
  `id_empresa` INT NOT NULL,
  PRIMARY KEY (`id_produto`),
  INDEX `id_empresa_idx` (`id_empresa` ASC),
  CONSTRAINT `id_empresa_fk`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `mydb`.`Empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Complemento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Complemento` (
  `id_complemento` INT NOT NULL AUTO_INCREMENT,
  `descricao_complemento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_complemento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto_Complemento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto_Complemento` (
  `id_produto` INT NOT NULL,
  `id_complemento` INT NOT NULL,
  PRIMARY KEY (`id_produto`, `id_complemento`),
  INDEX `id_complemento_fk_idx` (`id_complemento` ASC),
  CONSTRAINT `id_produto_fk`
    FOREIGN KEY (`id_produto`)
    REFERENCES `mydb`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_complemento_fk`
    FOREIGN KEY (`id_complemento`)
    REFERENCES `mydb`.`Complemento` (`id_complemento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `endereco_usuario` VARCHAR(45) NOT NULL,
  `email_usuario` VARCHAR(45) NOT NULL,
  `login_usuario` VARCHAR(45) NOT NULL,
  `senha_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_pedido_servidor` INT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_Pedido_Usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_Pedido_Usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto_Pedido` (
  `id_produto_pedido` INT NOT NULL,
  `id_produto_empresa` INT NOT NULL,
  `id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_produto_pedido`),
  INDEX `id_produto_empresa_idx` (`id_produto_empresa` ASC),
  INDEX `id_pedido_fk_idx` (`id_pedido` ASC),
  CONSTRAINT `id_produto_empresa_fk`
    FOREIGN KEY (`id_produto_empresa`)
    REFERENCES `mydb`.`Produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_pedido_fk`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `mydb`.`Pedido` (`id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Complemento_Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Complemento_Pedidos` (
  `id_produto_pedido` INT NOT NULL,
  `id_complemento` INT NOT NULL,
  PRIMARY KEY (`id_produto_pedido`),
  INDEX `id_complemento_fk_idx` (`id_complemento` ASC),
  CONSTRAINT `id_produto_pedido_fk`
    FOREIGN KEY (`id_produto_pedido`)
    REFERENCES `mydb`.`Produto_Pedido` (`id_produto_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_complemento_fk`
    FOREIGN KEY (`id_complemento`)
    REFERENCES `mydb`.`Complemento` (`id_complemento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `endereco_usuario` VARCHAR(45) NOT NULL,
  `email_usuario` VARCHAR(45) NOT NULL,
  `login_usuario` VARCHAR(45) NOT NULL,
  `senha_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `id_endereco` INT NOT NULL,
  `nome_endereco` VARCHAR(45) NOT NULL,
  `numero_endereco` VARCHAR(10) NOT NULL,
  `cep_endereco` VARCHAR(8) NOT NULL,
  `complemento_endereco` VARCHAR(45) NOT NULL,
  `apelido_endereco` VARCHAR(20) NOT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `id_usuario_fk_idx` (`id_usuario` ASC),
  CONSTRAINT `id_usuario_fk`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `id_pedido` INT NOT NULL AUTO_INCREMENT,
  `id_pedido_servidor` INT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_Pedido_Usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_Pedido_Usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
